// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $page from "./routes/page.tsx";
import * as $DemoButton from "./islands/DemoButton.tsx";
import * as $DemoCard from "./islands/DemoCard.tsx";
import * as $DemoFooter from "./islands/DemoFooter.tsx";
import * as $DemoHeader from "./islands/DemoHeader.tsx";
import * as $DemoInput from "./islands/DemoInput.tsx";
import * as $DemoLayout from "./islands/DemoLayout.tsx";
import * as $DemoLinkmap from "./islands/DemoLinkmap.tsx";
import * as $DemoLoader from "./islands/DemoLoader.tsx";
import * as $DemoMarkdown from "./islands/DemoMarkdown.tsx";
import * as $DemoMenu from "./islands/DemoMenu.tsx";
import * as $DemoNavigation from "./islands/DemoNavigation.tsx";
import * as $DemoPattern from "./islands/DemoPattern.tsx";
import * as $DemoText from "./islands/DemoText.tsx";
import * as $Menu from "./islands/Menu.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/page.tsx": $page,
  },
  islands: {
    "./islands/DemoButton.tsx": $DemoButton,
    "./islands/DemoCard.tsx": $DemoCard,
    "./islands/DemoFooter.tsx": $DemoFooter,
    "./islands/DemoHeader.tsx": $DemoHeader,
    "./islands/DemoInput.tsx": $DemoInput,
    "./islands/DemoLayout.tsx": $DemoLayout,
    "./islands/DemoLinkmap.tsx": $DemoLinkmap,
    "./islands/DemoLoader.tsx": $DemoLoader,
    "./islands/DemoMarkdown.tsx": $DemoMarkdown,
    "./islands/DemoMenu.tsx": $DemoMenu,
    "./islands/DemoNavigation.tsx": $DemoNavigation,
    "./islands/DemoPattern.tsx": $DemoPattern,
    "./islands/DemoText.tsx": $DemoText,
    "./islands/Menu.tsx": $Menu,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
