// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_chips_add from "./routes/api/chips/add.ts";
import * as $api_chips_edit from "./routes/api/chips/edit.ts";
import * as $api_chips_get from "./routes/api/chips/get.ts";
import * as $api_chips_list from "./routes/api/chips/list.ts";
import * as $button_index from "./routes/button/index.tsx";
import * as $chip_index from "./routes/chip/index.tsx";
import * as $demo from "./routes/demo.tsx";
import * as $gradient_index from "./routes/gradient/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $input_index from "./routes/input/index.tsx";
import * as $kbd_index from "./routes/kbd/index.tsx";
import * as $layout_index from "./routes/layout/index.tsx";
import * as $markdown_index from "./routes/markdown/index.tsx";
import * as $panel_panel from "./routes/panel/panel.tsx";
import * as $text_text from "./routes/text/text.tsx";
import * as $AddChip from "./islands/AddChip.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/chips/add.ts": $api_chips_add,
    "./routes/api/chips/edit.ts": $api_chips_edit,
    "./routes/api/chips/get.ts": $api_chips_get,
    "./routes/api/chips/list.ts": $api_chips_list,
    "./routes/button/index.tsx": $button_index,
    "./routes/chip/index.tsx": $chip_index,
    "./routes/demo.tsx": $demo,
    "./routes/gradient/index.tsx": $gradient_index,
    "./routes/index.tsx": $index,
    "./routes/input/index.tsx": $input_index,
    "./routes/kbd/index.tsx": $kbd_index,
    "./routes/layout/index.tsx": $layout_index,
    "./routes/markdown/index.tsx": $markdown_index,
    "./routes/panel/panel.tsx": $panel_panel,
    "./routes/text/text.tsx": $text_text,
  },
  islands: {
    "./islands/AddChip.tsx": $AddChip,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
