// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_chips_add from "./routes/api/chips/add.ts";
import * as $api_chips_edit from "./routes/api/chips/edit.ts";
import * as $api_chips_get from "./routes/api/chips/get.ts";
import * as $api_chips_list from "./routes/api/chips/list.ts";
import * as $demo from "./routes/demo.tsx";
import * as $index from "./routes/index.tsx";
import * as $DemoButton from "./islands/DemoButton.tsx";
import * as $DemoInput from "./islands/DemoInput.tsx";
import * as $DemoText from "./islands/DemoText.tsx";
import * as $KvAutocomplete from "./islands/KvAutocomplete.tsx";
import * as $Sidebar from "./islands/Sidebar.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/chips/add.ts": $api_chips_add,
    "./routes/api/chips/edit.ts": $api_chips_edit,
    "./routes/api/chips/get.ts": $api_chips_get,
    "./routes/api/chips/list.ts": $api_chips_list,
    "./routes/demo.tsx": $demo,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/DemoButton.tsx": $DemoButton,
    "./islands/DemoInput.tsx": $DemoInput,
    "./islands/DemoText.tsx": $DemoText,
    "./islands/KvAutocomplete.tsx": $KvAutocomplete,
    "./islands/Sidebar.tsx": $Sidebar,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
